[general]
domain=""
prompt="""
Please, keep conversation friendly and concise and 'safe for work'.
Please answer describing the found info items that were found. 
Discuss websites selling relevant products and recommended by other websites
The question:   
"""

[inner]
domain="inner.org"
prompt="""
Keep conversation 'safe for work', concise and friendly.
Discuss the links found in the website:  
"""

[recipes]
domain=""
prompt="""
Discuss and help to find the kosher recipes.
Please, keep conversation friendly and concise and 'safe for work'.
Please describe and discuss recipes that were found. 
"""

[gifts]
domain=""
prompt="""
Discuss and help to find gifts in amazon.com.
Please, keep conversation 'safe for work', friendly and concise.
Please describe and discuss the gifts that were found. 
"""


