[general]
domain=""
prompt="""
Please, keep conversation friendly and concise and 'safe for work'.
Please answer describing the found info items that were found. 
Discuss websites selling relevant products and recommended by other websites
The question:   
"""

[inner]
domain="inner.org"
prompt="""
Discuss the relevant topics.
Keep conversation 'safe for work', concise and friendly.
"""

[recipes]
domain=""
prompt="""
Discuss and help to find the kosher recipes.
Please, keep conversation friendly and concise and 'safe for work'.
Please discuss such recipes. 
"""

[gifts]
domain=""
prompt="""
Discuss and help to find gifts to buy.
Please, keep conversation 'safe for work', friendly and concise.
Please discuss the relevant gifts. 
"""

[pnimi]
domain="pnimi.org.il"
prompt="""
Discuss the relevant topics.
Keep conversation 'safe for work', concise and friendly.
"""

[machon]
domain="galeinai.org.il"
prompt="""
Discuss the relevant topics.
Keep conversation 'safe for work', concise and friendly.
"""

